[graveSettings]
generateGraves = true
retrievalType = "ON_USE"
dropType = "IN_INVENTORY"
dropPlayerHead = false
dropGraveBlock = false
requireGraveItem = false
generateEmptyGraves = false
priority = "GRAVE"
deleteEnchantments = ["minecraft:vanishing_curse"]
soulboundEnchantments = ["yigd:soulbound"]
trySoft = true
tryStrict = true
blacklistDimensions = []
graveInVoid = false
ignoreDeathTypes = []
graveSpawnHeight = 2
lastResort = "DROP_ITEMS"
defaultXpDrop = true
xpDropPercent = 50
tellDeathPos = false

[graveSettings.graveRobbing]
enableRobbing = false
onlyMurderer = false
afterTime = 0
timeType = "MINUTES"
robPriority = "INVENTORY"

[graveSettings.graveDeletion]
canDelete = false
afterTime = 1
timeType = "HOURS"
dropInventory = false

[graveSettings.blockUnderGrave]
generateBlockUnder = true
inOverWorld = "twigs:rocky_dirt"
inNether = "minecraft:netherrack"
inTheEnd = "minecraft:end_stone"
inCustom = "minecraft:dirt"

[graveSettings.graveRenderSettings]
useRenderFeatures = true
renderGraveSkull = false
renderGraveOwner = true
textShadow = true
adaptRenderer = true
glowingGrave = false
glowMinDistance = 10
[utilitySettings]
soulboundEnchant = true
[commandToggles]
retrieveGrave = true
